model = "gpt-5.3-codex"
model_reasoning_effort = "medium"
[projects."/home/dashverse/Codes/dashverse/frameo-ai"]
trust_level = "trusted"

[projects."/home/dashverse/Codes/dashverse/chat-on-canvas-tui-poc"]
trust_level = "trusted"

[projects."/home/dashverse/Codes/dashverse/infra"]
trust_level = "trusted"

[projects."/home/dashverse/Codes/dashverse/studio-chat"]
trust_level = "trusted"

[projects."/home/dashverse/Codes/dashverse/studio"]
trust_level = "trusted"

[projects."/home/dashverse/Codes/dashverse/mark-tool-poc"]
trust_level = "trusted"

[projects."/home/dashverse"]
trust_level = "trusted"

[notice.model_migrations]
"gpt-5.2-codex" = "gpt-5.3-codex"

[mcp_servers.context7]
args = ["-y", "@upstash/context7-mcp", "--api-key", "YOUR_API_KEY"]
command = "npx"
